name: build
channels:
  - conda-forge
  - mdtools
dependencies:
  # Base dependencies
  - python
  - pip
  - numpy
  - openmm
  - cvpack
  - pyyaml

  # Conda build
  - anaconda-client
  - conda-build
  - boa

  # Machine learning dependencies
  - pytorch
  - lightning

  # PyPI build
  - pip:
    - build
    - twine
